/planner_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    GridBased:
      allow_unknown: true
      analytic_expansion_max_length: 3.0
      analytic_expansion_ratio: 3.5
      angle_quantization_bins: 64
      cache_obstacle_heuristic: true
      change_penalty: 0.0
      cost_penalty: 2.0
      downsample_costmap: false
      downsampling_factor: 1
      lookup_table_size: 20.0
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 3.5
      minimum_turning_radius: 0.1
      motion_model_for_search: DUBIN
      non_straight_penalty: 1.2
      plugin: nav2_smac_planner/SmacPlannerHybrid
      retrospective_penalty: 0.025
      reverse_penalty: 1.0
      smooth_path: true
      smoother:
        do_refinement: true
        max_iterations: 1000
        tolerance: 1.0e-10
        w_data: 0.2
        w_smooth: 0.3
      tolerance: 0.5
    expected_planner_frequency: 10.0
    planner_plugins:
    - GridBased
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
    use_sim_time: true
